### Librerias

In [45]:
import pandas as pd

### Carga de datos

In [ ]:
df = pd.read_csv('../../data/raw_data_09-03-2026.csv',index_col=0)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7001 entries, 0 to 7000
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   apartment_id                 7001 non-null   int64
 1   name                         6998 non-null   object
 2   description                  6972 non-null   object
 3   host_id                      7001 non-null   int64
 4   neighbourhood_name           7001 non-null   object
 5   neighbourhood_district       4241 non-null   object
 6   room_type                    7001 non-null   object
 7   accommodates                 7001 non-null   int64
 8   bathrooms                    6969 non-null   float64
 9   bedrooms                     6972 non-null   float64
 10  beds                         6998 non-null   float64
 11  amenities_list               6984 non-null   object
 12  price                        6870 non-null   float64
 13  minimum_nights               7001 non-null   int64
 14  maximum_nights               7001 non-null   int64
 15  has_availability             6451 non-null   object
 16  availability_30              7001 non-null   int64
 17  availability_60              7001 non-null   int64
 18  availability_90              7001 non-null   int64
 19  availability_365             7001 non-null   int64
 20  number_of_reviews            7001 non-null   int64
 21  first_review_date            5747 non-null   object
 22  last_review_date             5746 non-null   object
 23  review_scores_rating         5674 non-null   float64
 24  review_scores_accuracy       5665 non-null   float64
 25  review_scores_cleanliness    5671 non-null   float64
 26  review_scores_checkin        5660 non-null   float64
 27  review_scores_communication  5669 non-null   float64
 28  review_scores_location       5659 non-null   float64
 29  review_scores_value          5659 non-null   float64
 30  is_instant_bookable          7001 non-null   object
 31  reviews_per_month            5747 non-null   float64
 32  country                      7001 non-null   object
 33  city                         7001 non-null   object
 34  insert_date                  7001 non-null   object
dtypes: float64(12), int64(10), object(13)
memory usage: 1.9+ MB

In [48]:
df[['first_review_date','last_review_date','number_of_reviews','reviews_per_month','insert_date']]

,first_review_date,last_review_date,number_of_reviews,reviews_per_month,insert_date
0,02/01/2010,05/09/2017,78,75.0,31/07/2018
1,10/10/2014,15/07/2018,33,52.0,10/01/2020
2,05/01/2011,22/07/2019,148,142.0,29/07/2019
3,13/03/2012,04/01/2020,292,306.0,10/01/2020
4,08/07/2011,08/08/2018,36,39.0,19/02/2019
...,...,...,...,...,...
6996,13/03/2020,13/03/2020,1,7.0,23/04/2020
6997,NaN,NaN,0,NaN,30/08/2018
6998,23/09/2018,23/09/2018,1,6.0,31/12/2019
6999,NaN,NaN,0,NaN,31/07/2018
7000,07/08/2018,02/01/2020,48,216.0,28/05/2020

Seleccionamos solo las columnas que necesitamos

In [49]:
df=df[['apartment_id','room_type','price','has_availability','availability_30','availability_60','availability_90','availability_365','review_scores_rating','first_review_date','last_review_date','number_of_reviews','reviews_per_month','city','insert_date']].copy()

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7001 entries, 0 to 7000
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   apartment_id          7001 non-null   int64
 1   room_type             7001 non-null   object
 2   price                 6870 non-null   float64
 3   has_availability      6451 non-null   object
 4   availability_30       7001 non-null   int64
 5   availability_60       7001 non-null   int64
 6   availability_90       7001 non-null   int64
 7   availability_365      7001 non-null   int64
 8   review_scores_rating  5674 non-null   float64
 9   first_review_date     5747 non-null   object
 10  last_review_date      5746 non-null   object
 11  number_of_reviews     7001 non-null   int64
 12  reviews_per_month     5747 non-null   float64
 13  city                  7001 non-null   object
 14  insert_date           7001 non-null   object
dtypes: float64(3), int64(6), object(6)
memory usage: 875.1+ KB

### Limpieza

Nulos

In [51]:
df.isnull().sum()

apartment_id               0
room_type                  0
price                    131
has_availability         550
availability_30            0
availability_60            0
availability_90            0
availability_365           0
review_scores_rating    1327
first_review_date       1254
last_review_date        1255
number_of_reviews          0
reviews_per_month       1254
city                       0
insert_date                0
dtype: int64

In [52]:
# df=df.dropna(subset=['price'])
df['price_missing'] = df['price'].isna()

Duplicados

Se ordena el dataset por identificador y fecha para conservar únicamente el registro más reciente en la tabla principal, archivando las versiones anteriores en un DataFrame secundario a modo de histórico.

In [53]:
df = df.sort_values(by=['apartment_id','insert_date'], ascending=[True, False])


dfanunciosantiguos = df[df.duplicated(subset=['apartment_id'],keep=False)].copy()

df = df.drop_duplicates(subset=['apartment_id'], keep='first')

In [54]:
dfanunciosantiguos

,apartment_id,room_type,price,has_availability,availability_30,availability_60,availability_90,availability_365,review_scores_rating,first_review_date,last_review_date,number_of_reviews,reviews_per_month,city,insert_date,price_missing
22,144471,Private room,470.0,VERDADERO,22,52,82,357,870.0,04/07/2011,04/08/2016,32,42.0,barcelona,12/09/2017,False
23,144471,Private room,490.0,VERDADERO,19,49,79,354,880.0,04/07/2011,15/08/2018,34,38.0,barcelona,10/10/2018,False
25,157327,Entire home/apt,5000.0,VERDADERO,26,56,86,361,800.0,18/08/2015,18/08/2015,1,3.0,girona,30/08/2018,False
24,157327,Entire home/apt,NaN,VERDADERO,27,57,87,362,800.0,18/08/2015,18/08/2015,1,2.0,girona,30/04/2020,True
51,343864,Entire home/apt,1390.0,VERDADERO,0,5,35,307,940.0,17/06/2014,14/10/2018,7,13.0,barcelona,07/11/2018,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6934,26987062,Private room,170.0,VERDADERO,0,0,0,0,NaN,NaN,NaN,0,NaN,madrid,11/09/2018,False
6965,27141824,Entire home/apt,500.0,VERDADERO,30,60,90,180,940.0,05/08/2018,16/03/2020,65,287.0,madrid,13/06/2020,False
6964,27141824,Entire home/apt,450.0,VERDADERO,18,48,57,148,930.0,05/08/2018,08/07/2019,34,30.0,madrid,10/07/2019,False
6999,27245117,Entire home/apt,1100.0,VERDADERO,2,31,61,151,NaN,NaN,NaN,0,NaN,girona,31/07/2018,False
7000,27245117,Entire home/apt,950.0,VERDADERO,23,38,51,179,980.0,07/08/2018,02/01/2020,48,216.0,girona,28/05/2020,False

In [55]:
print(f"Apartamentos únicos listos para análisis (DF principal): {len(df)}")
print(f"Registros antiguos guardados en el histórico: {len(dfanunciosantiguos)}")

Apartamentos únicos listos para análisis (DF principal): 6733
Registros antiguos guardados en el histórico: 529

In [56]:
es_unico = df['apartment_id'].is_unique
print(f"¿Son todos los IDs únicos?: {es_unico}")

¿Son todos los IDs únicos?: True

In [57]:
# Estandarización de texto: formato título para los nombres de las ciudades
df['city'] = df['city'].str.title()

### Transformación

Para garantizar la integridad del análisis, se ha llevado a cabo un proceso de estandarización estructural del dataset. Esto ha incluido el casting de variables (conversión de las columnas a sus tipos de datos nativos correspondientes, como numéricos, booleanos o fechas) para permitir operaciones matemáticas correctas. Asimismo, se han corregido inconsistencias y anomalías de formato detectadas en varias columnas, asegurando que la información sea coherente y esté optimizada para la fase de modelado.

Se recalcula la columna de reviews_per_month ya que el equipo se ha dado cuenta de que los numeros no son correctos
Convierto las columnas de las reseñas a formato fecha para poder calcular el tiempo pasado desde 'first_review_date'(primera fecha de la que disponemos) hasta la 'insert_date'(ultima fecha de la que disponemos) para que el calculo sea mas cercano a la realidad

In [58]:



df['first_review_date']= pd.to_datetime(df['first_review_date'], dayfirst=True)

df['last_review_date']= pd.to_datetime(df['last_review_date'], dayfirst=True)
df['insert_date'] = pd.to_datetime(df['insert_date'], dayfirst=True)

# Calculamos los meses transcurridos
meses = (df['insert_date'] - df['first_review_date']).dt.days / 30.4



df['reviews_per_month'] = round(((df['number_of_reviews'] / meses)),2)

In [59]:


df['review_scores_rating']=df['review_scores_rating']/10
df['review_scores_rating']=df['review_scores_rating'].astype('Int64')

# Esta línea convierte lo que no sea 'VERDADERO' a False (Asumiendo que si esta nulo es porque no tiene disponibilidad)
df['has_availability'] = df['has_availability'] == 'VERDADERO'

### Creación de variables

Se ha generado una nueva variable booleana para identificar los apartamentos con valoraciones superiores a 80

In [60]:
df['reviews 80+']=df['review_scores_rating'] >= 80

In [61]:
df

,apartment_id,room_type,price,has_availability,availability_30,availability_60,availability_90,availability_365,review_scores_rating,first_review_date,last_review_date,number_of_reviews,reviews_per_month,city,insert_date,price_missing,reviews 80+
0,11964,Private room,400.0,True,7,20,40,130,97,2010-01-02,2017-09-05,78,0.76,Malaga,2018-07-31,False,True
1,21853,Private room,170.0,True,0,0,0,162,92,2014-10-10,2018-07-15,33,0.52,Madrid,2020-01-10,False,True
2,32347,Entire home/apt,990.0,True,26,31,31,270,98,2011-01-05,2019-07-22,148,1.44,Sevilla,2019-07-29,False,True
3,35379,Private room,400.0,True,9,23,49,300,94,2012-03-13,2020-01-04,292,3.10,Barcelona,2020-01-10,False,True
4,35801,Private room,900.0,True,0,19,49,312,97,2011-07-08,2018-08-08,36,0.39,Girona,2019-02-19,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,27237828,Entire home/apt,1500.0,True,22,47,77,78,100,2018-08-26,2018-08-26,1,7.60,Girona,2018-08-30,False,True
6996,27241318,Entire home/apt,3130.0,True,26,37,37,243,100,2020-03-13,2020-03-13,1,0.74,Mallorca,2020-04-23,False,True
6997,27244243,Entire home/apt,990.0,True,24,40,40,40,<NA>,NaT,NaT,0,NaN,Girona,2018-08-30,False,<NA>
6998,27244794,Entire home/apt,720.0,True,0,0,0,0,100,2018-09-23,2018-09-23,1,0.07,Girona,2019-12-31,False,True
6999,27245117,Entire home/apt,1100.0,True,2,31,61,151,<NA>,NaT,NaT,0,NaN,Girona,2018-07-31,False,<NA>

Se genera una archivo CSV con los datos limpios y otro con los anuncios antiguos

In [ ]:
# Generación del CSV bloqueada (el archivo ya se encuentra en el directorio del proyecto).
# df.to_csv('../../data/clean_data_nulos_09-03-2026.csv', index=False)

#dfanunciosantiguos.to_csv('../../data/Anuncios antiguos_09-03-2026.csv', index=False)